# Generated by Django 2.0.4 on 2018-05-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('orderItemId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Suppliers')),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='supplierItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.SupplierItems'),
        ),
    ]
