# Generated by Django 2.0.4 on 2018-05-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierItems',
            fields=[
                ('supplierItemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemCode', models.CharField(max_length=255)),
                ('itemName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierId', models.AutoField(primary_key=True, serialize=False)),
                ('supplierName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='supplieritems',
            name='supplierId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Suppliers'),
        ),
    ]
